// 30 new simulated members (T1–T30), different from S1–S20: run through the real assessment logic, the engine and the rule checks,
const __path = require('path'); require('fs').mkdirSync(__path.join(__dirname, 'out'), { recursive: true }); process.chdir(__path.join(__dirname, 'out'));
// plus a per-member expectation and the "Not right for me" rule for every practice.
const fs = require('fs');
const { M, AO, check, E, DATA, toFeatures, QUESTIONS } = require('./simcore.js');
const has = (o, f) => o.months.flat().some(x => x.fam === f);
const note = (o, k) => o.pilot.some(n => n[0] === k);
const fams = o => o.months[0].map(x => x.fam);
const T = [
  [M('T1 Graça, 72, retired, not sure, 45–60 min', { q1: ['I’m not sure yet'], q2: '70 or over', q3: 'Not currently working', q55: 'About 45–60 minutes' }), o => o.months[0].length >= 3 || 'fewer than 3 practices'],
  [M('T2 Pedro, 41, asthma, wants Movement, big', { q1: [AO('Movement')], q4: ['A lung condition, such as asthma or COPD'], q20: '1', q21: '30', q22: '0', q56: "I'm ready for a bigger challenge", q27: ['Build general fitness'] }), o => note(o, 'Lung condition') || 'no lung-condition Pilot note'],
  [M('T3 Helena, 63, high blood pressure, inactive, Prevention', { q1: [AO('Prevention')], q2: '60-69', q4: ['High blood pressure'], q20: '0', q22: '0', q46: 'More than 2 years ago', q52: ['Keeping up with check-ups'] }), o => (note(o, 'Blood pressure') && has(o, 'Routine check-ups')) || 'missing BP note or check-ups'],
  [M('T4 Sofia, 28, vegetarian, protein goal', { q1: [AO('Nutrition')], q2: '18-29', q11: ['Dietary restriction or preference (for example vegetarian, vegan, halal or kosher)'], q9: ['Getting enough protein'], q7: { veg: '5 or more portions', protein: 'One', cooked: 'More than 5', grains: '3–5 days a week', beans: '3–5 days a week', sugary: 'Rarely or never', processed: 'Rarely or never', nuts: '3–5 days a week', salt: 'Rarely or never' } }), o => (note(o, 'Food') && has(o, 'Protein at meals')) || 'missing food note or protein practice'],
  [M('T5 Bruno, 36, shift worker, insomnia, anxious, Sleep and Mind', { q1: [AO('Sleep'), AO('Mind')], q3: 'Shift work, including nights', q12: '5-6', q13: ['It takes me a long time to fall asleep', 'I wake during the night and find it hard to get back to sleep'], q32: { anx1: 'More than half the days', anx2: 'More than half the days', dep1: 'Several days', dep2: 'Several days' } }), o => (note(o, 'Shift work') && note(o, 'PHQ-4 positive')) || 'missing shift or PHQ note'],
  [M('T6 Marta, 33, breastfeeding, Sleep', { q1: [AO('Sleep')], q6: 'Breastfeeding', q12: '5-6', q18: ['Getting more sleep', 'Waking feeling rested'] }), o => true],
  [M('T7 Rui, 47, higher-risk drinking, wants Mind', { q1: [AO('Mind')], q43: '4 or more times a week', q44: '5-6', q45: 'Weekly', q33: ['Managing stress'] }), o => note(o, 'AUDIT-C 8+') || 'no AUDIT note'],
  [M('T8 Alice, 55, ex-smoker, Prevention', { q1: [AO('Prevention')], q40: { tobacco: "I used to, but I've stopped", vape: 'Never' }, q52: ['Keeping up with check-ups', 'Keeping my mind active by learning new things'] }), o => true],
  [M('T9 Diogo, 39, occasional smoker, wants to stop, tried before, small', { q1: [AO('Prevention')], q40: { tobacco: 'Occasionally', vape: 'Never' }, q41: 'Yes, in the next month', q42: 'Yes', q56: "Small, easy steps. I'm not sure how much I can manage right now" }), o => has(o, 'Trying again to quit') || 'no stop-smoking support'],
  [M('T10 Kátia, 30, athlete, performance, gym, big, 4h+', { q1: [AO('Movement')], q20: '6', q21: '90', q22: '3 or more', q26: ['Gym or studio', 'Outdoors'], q27: ['Improve performance', 'Build strength'], q55: 'More than 4 hours', q56: "I'm ready for a bigger challenge" }), o => !has(o, 'Building up cardio') || 'beginner cardio for an athlete'],
  [M('T11 Luís, 45, desk job, very sedentary, small steps', { q1: [AO('Movement')], q20: '0', q22: '0', q23: 'More than 10', q24: 'Fewer than 5,000', q56: "Small, easy steps. I'm not sure how much I can manage right now", q55: 'About 45–60 minutes' }), o => o.months[0].filter(x => x.role === 'Priority').every(x => ['Learning', 'All levels'].includes(x.row.l) || x.atBaseline) || 'above Learning'],
  [M('T12 Joana, 50, knee pain, wants strength', { q1: [AO('Movement')], q29: ['Ongoing pain', 'A joint or mobility limitation'], q22: '0', q27: ['Build strength'] }), o => true],
  [M('T13 André, 24, lonely, heavy social media, Connection', { q1: [AO('Connection')], q2: '18-29', q31: 'More than 2 hours', q36: { phone: 'Once', meet: 'Never', group: 'Never', volunteer: 'Never' }, q37: ['None of these'], q38: ['Meeting new people', 'A stronger sense of belonging'] }), o => has(o, 'Reaching out') || 'the High signal (rarely sees anyone) is not answered'],
  [M('T14 Filipa, 42, opts out of everything optional, Mind', { q1: [AO('Mind'), AO('Nutrition')], q57: ['Tracking or counting what I eat', 'Using apps or devices to track things', 'Eating windows or fasting', 'Meditation', 'Journalling or writing', 'Early-morning activities', 'Practices involving physical affection or touch'], q33: ['Managing stress', 'Enjoyment and positive experiences'], q9: ['When I eat, such as late-evening eating'] }), o => true],
  [M('T15 Nuno, 52, prefers not to say', { q2: 'Prefer not to say', q3: 'Prefer not to say', q4: ['Prefer not to say'], q6: 'Prefer not to say', q11: ['Prefer not to say'], q29: ['Prefer not to say'], q1: [AO('Nutrition')] }), o => !has(o, 'Daily eating window') || 'eating window despite "prefer not to say" on food'],
  [M('T16 Inês, 38, wants purpose and enjoyment', { q1: [AO('Mind')], q33: ['A greater sense of purpose', 'Enjoyment and positive experiences'], q34: ['None of these'] }), o => true],
  [M('T17 Tomás, 34, wants focus, already does focused work', { q1: [AO('Mind')], q33: ['Focus and concentration'], q34: ['Setting aside focused work time'] }), o => !has(o, 'Focused work') || 'offered focused work they already do'],
  [M('T18 Carlos, 58, under 5 hours, snores', { q1: [AO('Sleep')], q12: 'Less than 5', q14: 'Yes', q18: ['Getting more sleep'] }), o => note(o, 'Snoring') || o.pilot.some(n => /snor|breath/i.test(n[0] + n[1])) || 'no snoring note'],
  [M('T19 Rita, 27, late caffeine and screens, Sleep, small', { q1: [AO('Sleep')], q15: 'After 6pm', q19: ['Screens or technology', 'Caffeine'], q56: "Small, easy steps. I'm not sure how much I can manage right now", q17: { daylight: "I haven't tried it", dim: "I haven't tried it", regular: "I haven't tried it", alcohol: "I haven't tried it", winddown: "I haven't tried it", tasks: "I haven't tried it", cool: 'I do this now', dark: 'I do this now', quiet: 'I do this now', screens: "I haven't tried it", phone: "I haven't tried it", work: 'I do this now', naps: 'I do this now', pro: "I haven't tried it", share: "I haven't tried it" } }), o => o.foundations.some(h => h.f === 'Caffeine timing') || 'no caffeine foundation'],
  [M('T20 Leonor, 44, low mood, no meditation, Mind', { q1: [AO('Mind')], q32: { anx1: 'Several days', anx2: 'More than half the days', dep1: 'More than half the days', dep2: 'More than half the days' }, q57: ['Meditation'], q33: ['Managing difficult emotions'] }), o => (!has(o, 'Meditation') && !has(o, 'Expressive writing')) || 'meditation or expressive writing offered'],
  [M('T21 Vasco, 61, diabetes medicine, wants meal timing', { q1: [AO('Nutrition')], q4: ['Diabetes (including if you take insulin or other blood-sugar medicine)'], q9: ['When I eat, such as late-evening eating'], q16: 'Less than 1 hour', q20: '3', q21: '60' }), o => (!has(o, 'Daily eating window') && note(o, 'Medication')) || 'eating window or no medication note'],
  [M('T22 Amélia, 66, kidney disease, inactive, Movement', { q1: [AO('Movement')], q2: '60-69', q4: ['Kidney disease'], q20: '0', q22: '0' }), o => o.months.flat().filter(x => x.area === 'Movement').every(x => x.row.l === 'Learning' || x.row.l === 'All levels') || 'Movement above Learning'],
  [M('T23 Clara, 31, pregnant, Movement and Mind', { q1: [AO('Movement'), AO('Mind')], q6: 'Pregnant', q33: ['Managing stress', 'Switching off and relaxing'], q20: '2', q21: '30' }), o => !has(o, 'Yoga for stress') || 'yoga offered in pregnancy'],
  [M('T24 Miguel, 40, already strong everywhere, not sure, 2–4h', { q1: ['I’m not sure yet'], q55: '2-4 hours', q7: { veg: '5 or more portions', protein: 'All of them', cooked: 'More than 5', grains: '6–7 days a week', beans: '3–5 days a week', sugary: 'Rarely or never', processed: 'Rarely or never', nuts: '3–5 days a week', salt: 'Rarely or never' }, q12: '7-8', q20: '5', q21: '60', q22: '3 or more', q24: '10,000 or more', q30: 'More than 3 hours', q51: 'Several times a week', q43: 'Never' }), o => o.months[0].length >= 3 || 'fewer than 3'],
  [M('T25 Sara, 35, it varies, sunburn and hearing', { q1: [AO('Prevention')], q55: 'It varies', q48: ["I've been sunburnt, or used a sunbed, in the past 12 months", 'I often find it hard to follow conversations, or ask people to repeat themselves'], q52: ['Protecting my skin from the sun', 'Protecting my hearing'] }), o => (note(o, 'Hearing') && has(o, 'Avoiding sunburn')) || 'missing hearing note or sun practice'],
  [M('T26 Paula, 46, carer, short on time, Connection and Sleep', { q1: [AO('Connection'), AO('Sleep')], q19: ['Caring or family responsibilities'], q55: 'About 45–60 minutes', q36: { phone: 'Weekly or more', meet: 'Once', group: 'Never', volunteer: 'Never' }, q38: ['More time with friends or family'] }), o => o.minutes[0] <= o.budget || 'over time'],
  [M('T27 Henrique, 57, nut allergy, heart health', { q1: [AO('Nutrition')], q11: ['Nut allergy'], q9: ['Heart health: less salt and more nuts'], q7: { veg: '3-4 portions', protein: 'Two', cooked: '3–5', grains: '3–5 days a week', beans: '1–2 days a week', sugary: '1–2 days a week', processed: '1–2 days a week', nuts: 'Rarely or never', salt: '6–7 days a week' } }), o => (!has(o, 'Nuts') && has(o, 'Salt')) || 'nuts offered or salt missing'],
  [M('T28 Teresa, 68, rarely learns new things, Prevention', { q1: [AO('Prevention')], q2: '60-69', q51: 'Rarely or never', q52: ['Keeping my mind active by learning new things'] }), o => has(o, 'Learning new skills') || 'no learning practice'],
  [M('T29 Jorge, 74, fall last year, wants Mind', { q1: [AO('Mind')], q2: '70 or over', q29: ['A fall in the past 12 months'], q33: ['Rest and recovery'] }), o => (has(o, 'Balance') && note(o, 'Fall')) || o.pilot.some(n => /fall/i.test(n[0])) && has(o, 'Balance') || 'no balance practice or fall note'],
  [M('T30 Lara, 26, vapes, wants to stop now, food difficulties, Mind', { q1: [AO('Prevention'), AO('Mind')], q40: { tobacco: 'Never', vape: 'Daily' }, q41: 'Yes, in the next month', q42: 'No', q11: ['A difficult relationship with food'], q9: ['When I eat, such as late-evening eating'] }), o => (has(o, 'Stopping vaping') && !has(o, 'Daily eating window') && !has(o, 'Gap between eating and bed')) || 'no vaping support or meal-timing practice offered'],
];
const R = ['time', 'routine', 'already', 'pillar', 'health', 'other'];
const out = []; let total = 0, expFail = 0, nrN = 0;
fs.writeFileSync('personas30.json', JSON.stringify(T.map(t => t[0])));
for (const [s, exp] of T) {
  const f = toFeatures(s.A);
  const o = E.plan(JSON.parse(JSON.stringify(f))), o2 = E.plan(JSON.parse(JSON.stringify(f)));
  const sig = x => JSON.stringify([x.months.map(m => m.map(y => [y.fam, y.row.l, y.change, y.why])), x.themes, x.foundations.map(h => h.f), x.pilot]);
  const det = sig(o) === sig(o2), issues = check(f, o), e = exp(o);
  if (e !== true) { issues.push('Expectation: ' + e); expFail++; }
  const nr = o.months[0].map((x, i) => R.map(r => { nrN++; const z = o.notRight(0, i, r); return [x.fam, r, z.action, (z.options || []).map(y => `${y.area} · ${y.fam} (${y.row.l})`)]; })).flat();
  total += issues.length;
  const seen = QUESTIONS.filter(q => !q.show || q.show(s.A)).length;
  out.push({ name: s.name, seen, f, o, det, issues, nr });
  console.log('\n==', s.name, '| pri', o.pri.join('+'), '| light', o.light.join('+') || '-', '| new min', o.minutes.map(Math.round).join('/'), 'of', o.budget, '| seen', seen, '| det', det);
  o.months[0].forEach((x, i) => console.log('  ', x.role.padEnd(13), x.area.padEnd(10), (x.fam + ' (' + x.row.l + ', ' + x.row.ev + ')').padEnd(56), o.months[1][i].change.padEnd(9), o.months[2][i].change.padEnd(9), '|', x.why.slice(0, 70), x.note ? '[' + x.note + ']' : ''));
  console.log('   themes:', o.themes.map(t => t[1]).join(', '), '| foundations:', o.foundations.map(h => h.f).join(', '));
  console.log('   pilot:', o.pilot.map(n => n[0]).join(', '));
  if (issues.length) console.log('   ISSUES:', issues);
}
fs.writeFileSync('sims30.json', JSON.stringify(out.map(r => ({ name: r.name, seen: r.seen, deterministic: r.det, issues: r.issues, wish: r.f.wish, change: r.f.change, time: r.f.time, optout: r.f.optout,
  pri: r.o.pri, light: r.o.light, minutes: r.o.minutes, target: r.o.target, budget: r.o.budget, status: r.o.status, themes: r.o.themes, foundations: r.o.foundations.map(h => [h.p, h.t]), pilot: r.o.pilot, nr: r.nr,
  months: r.o.months.map(m => m.map(x => ({ role: x.role, area: x.area, fam: x.fam, level: x.row.l, ev: x.row.ev, text: x.row.w + ' ' + x.row.d + '. ' + x.row.t, why: x.why, change: x.change, note: x.note || '', extra: r.o.extraMinutes(x.row), target: x.row.tg }))) })), null, 1));
console.log('\nTOTAL issues', total, '| expectations failed', expFail, '| all deterministic', out.every(r => r.det), '| avg questions seen', (out.reduce((t, r) => t + r.seen, 0) / out.length).toFixed(1), '| not-right checks', nrN);
